POST http://127.0.0.1:8000/login
Content-Type: application/json

{
  "email": "ayaneshx@ayaneshdev.xyz",
  "password": "heisenberg"
}

###

DELETE http://127.0.0.1:8000/logout
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3Q6ODAwMCIsImF1ZCI6Imh0dHA6XC9cL2xvY2FsaG9zdDo4MDAwIiwiaWF0IjoxNjA5OTQyODY1LCJuYmYiOjE2MDk5NDI4NjUsImV4cCI6MTYwOTk0Mjk4NSwidXNlcl9pZCI6MTZ9.BPeWBVNIyQQgTECEY4KmtF_XpXJ3dLoLh-IWH2ezm_A eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3Q6ODAwMCIsImF1ZCI6Imh0dHA6XC9cL2xvY2FsaG9zdDo4MDAwIiwiaWF0IjoxNjA5OTQyODY1LCJuYmYiOjE2MDk5NDI4NjUsInVzZXJfaWQiOjE2fQ.4lLK7E4kIM4ccbi5E5jHxI7mXQK8eIaFqRt9Fl4pOSE

###
GET http://127.0.0.1:8000/get-users
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3Q6ODAwMCIsImF1ZCI6Imh0dHA6XC9cL2xvY2FsaG9zdDo4MDAwIiwiaWF0IjoxNjA5OTQ0MDMyLCJuYmYiOjE2MDk5NDQwMzIsImV4cCI6MTYwOTk0NDE1MiwidXNlcl9pZCI6MTZ9.3fx0bvcwVNsDKa5mLV4or9kDbYASi7h2DO3Lxh2MWs4 eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3Q6ODAwMCIsImF1ZCI6Imh0dHA6XC9cL2xvY2FsaG9zdDo4MDAwIiwiaWF0IjoxNjA5OTQ0MDMyLCJuYmYiOjE2MDk5NDQwMzIsInVzZXJfaWQiOjE2fQ._Q-kaWNJ3_4OZEQYY5_0UE6sM5jlXR758wPNRR8hfPU